- Jenkinsfile
- package.json
> [FEAT] Added vault and registry

- Jenkinsfile
> [FIX] Jenkinsfile - read registry from environment

- Jenkinsfile
- nightwatch.conf.js
- package.json
> [CHORE] added tests and added preversion phase to package.json

- index.html
- src/DropDownItems.vue
- src/MolgenisMenu.vue
- src/href.js
Two main changes:
* type property has become lowercase so the code should check for 'plugin' instead of 'PLUGIN'
* href property is missing, code should combine id and params into url
(Used to be done in url getter of MenuItemToMolgenisUiMenuItemAdapter.java)
> feat: Upgrade to simplified menu json

- Jenkinsfile
- package.json
> [CHORE] Fix artifact name and hubot message

- .gitignore
- nightwatch.config.js
- src/components/DropDownItems.vue
- src/components/NavBar.vue
- src/exampleMenu.ts
- src/href.ts
- src/types.ts
- tests/unit/__snapshots__/NavBar.spec.ts.snap
> [FIX] components for complying to new menu modal

- CHANGELOG.md
> Add change log + prepare for release of 0.2.0

- src/main.js
> fix(main): Remove polyfill from the menu

- CHANGELOG.md
- README.md
- src/components/NavBar.vue
- tests/e2e/specs/test.js
- tests/unit/components/__snapshots__/NavBar.spec.ts.snap
+ update e2e with check
+ update snapshot to include active class
Fix #29
> Fix #29  Add missing object ref to fix active class not being set

- CHANGELOG.md
> Update change log to prepare for 0.3.0 release.

- src/service/CookieService.ts
- tests/unit/CookieWall.spec.ts
- tests/unit/service/CookieService.spec.ts
> [TASK] fix linting issues

- CHANGELOG.md
> changed changelog

- src/components/FooterComponent.vue
- src/exampleFooter.ts
- tests/unit/components/FooterComponent.spec.ts
- tests/unit/components/__snapshots__/FooterComponent.spec.ts.snap
> Render additional footer message as html

- src/components/NavBar.vue
- src/exampleMenu.ts
- tests/e2e/specs/test.js
- tests/unit/components/__snapshots__/NavBar.spec.ts.snap
Copy paste issue, the image above navbar was forgotten when the code moved. Added a test for the
logo above menu bar, to make sure the issue won't occur again since we had many issues with this
feature. Also added a max width to fix another issue (https://github.com/molgenis/molgenis/issues/8430) that was already present in the old menu as
well.
Fixes: molgenis/molgenis#8422
> fix(menu): Add top menu image to navbar

- .github/PULL_REQUEST_TEMPLATE.md
Removed - [] Updated flow typing
No flow script in this repo
> Update request template

- src/components/NavBar.vue
- tests/unit/components/__snapshots__/NavBar.spec.ts.snap
Use of style is static within component therefore dynamic ( js ) usage is overly complex and can be replaced with style rule.
> refactor: move top log style from js to css

- README.md
- public/index.html
- public/sticky-footer.css
- src/App.vue
- src/components/FooterComponent.vue
- Use setup described in sticky footer.css
- Remove footer component style
- Swap out vue image for demo text
Setup to move towards demo page with knobs to play around with things like sticky/fixed headers and other page context stuff.
> task: setup demo page similar to molgenis

- Jenkinsfile
- README.md
- package.json
> [CHORE] Add autorelease

- README.md
- src/App.vue
- src/components/PageComponent.vue
- tests/e2e/specs/test.js
- vue.config.js
Page component includes Header, Footer and Cookiewall and includes the context fetch from the backend
For easy molgenis page development
> feat: Add PageComponent

- package.json
- src/components/FooterComponent.vue
- src/exampleFooter.ts
- src/types.ts
- tests/unit/components/__snapshots__/FooterComponent.spec.ts.snap
- vue.config.js
- yarn.lock
fixes: https://github.com/molgenis/molgenis/issues/8423
Removed dependency on molgenis (/app-ui-context)
Getting URL's externally from a static source (`molgenis/molgenis-core-ui/src/main.recources/js/bootstrap-4/footer/molgenis-footer.js`?)  but having the text locally static obfuscates without having a clear reason.
- User documentation updated
- No warnings during install
> fix: add missing citation #8423

- README.md
- describes instalation using yarn/npm
- use of css
- installation of peer depedancies ( with note on vue cli 3 usage)
> task: extend documentation with description on installation of component

- README.md
- package.json
- src/module.ts
Needed to have the separate components of the context to be deployed in the MOLGENIS repository. At this stage we did not do anything with the NavBar component anyway.
> feat(module.ts): added module.ts to expose compiled components

- src/components/CookieWall.vue
- src/components/DropDownItems.vue
- src/components/HeaderImage.vue
- src/components/NavBar.vue
It is a dev dependency
- User documentation updated
- No warnings during install
- Added Feature/Fix to release notes
> fix: do not depend on Vue

- src/components/NavBar.vue
> refactor(css): Move hover style to component css

- src/components/NavBar.vue
> fix: add hover style to dropdown toggle

- src/components/NavBar.vue
Add label with 'Home' text in case of missing logo
> Fix(NavBar): Fix molgenis #8681 , Missing fallback label

- CHANGELOG.md
- package.json
* Fix(NavBar): Fix molgenis #8681 , Missing fallback label ([df0f61a](https://github.com/molgenis/molgenis-ui-context/commit/df0f61a))
> chore(release): 1.3.3 [skip ci]

- src/components/NavBar.vue
> fix: fallback home link

- CHANGELOG.md
- package.json
> chore(release): 1.3.4 [skip ci]

- package.json
> task: fix build scripts, remove test as these are called by jenkins file

- src/service/EventUtilService.ts
For more info, see https://github.com/mgechev/angular-seed/issues/901
> fix: force ts setTimeout definition from window

- src/components/FooterComponent.vue
- tests/unit/components/__snapshots__/FooterComponent.spec.ts.snap
> fix: update footer text

- src/types.ts
> fix: add email and username to Context

- src/types.ts
> feat: make email and username mandatory

- tests/unit/fixtures/context.ts
> test: fix context fixture

- src/types.ts
- tests/unit/fixtures/context.ts
> fix: add roles to context type

- src/components/CookieWall.vue
- src/components/HeaderComponent.vue
- src/components/PageComponent.vue
- tests/e2e/specs/test.js
> fix: cookiewall is full width and infront of content

- src/components/DropDownItems.vue
> fix: Closes #103 use index to generate key in submenu item

- Jenkinsfile
- nightwatch.config.js
- tests/e2e/specs/test.js
-  No warnings during install
-  Added Feature/Fix to release notes
> chore: fix saucelabs integration

- src/App.vue
- src/components/NavBar.vue
- tests/unit/components/NavBar.spec.ts
fix: https://github.com/molgenis/molgenis-frontend/issues/666
- User documentation updated
- No warnings during install
- Added Feature/Fix to release notes
> fix: dont set navbar-expanded-md on mobile #666
